# Generated by Django 4.2.3 on 2023-07-10 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connexionapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='connexionuser',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connexionapi.gender'),
        ),
        migrations.AddField(
            model_name='connexionuser',
            name='orientation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connexionapi.orientation'),
        ),
    ]
