# Generated by Django 4.2.3 on 2023-07-18 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connexionapi', '0002_gender_orientation_connexionuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=150)),
                ('image', models.CharField(max_length=50)),
                ('connexion_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connexionapi.connexionuser')),
            ],
        ),
    ]
