# Generated by Django 4.2.3 on 2023-07-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connexionapi', '0004_post_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('connexion_user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to='connexionapi.connexionuser')),
                ('connexion_user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to='connexionapi.connexionuser')),
            ],
        ),
        migrations.AddField(
            model_name='connexionuser',
            name='friends',
            field=models.ManyToManyField(related_name='approvedfriends', through='connexionapi.FriendRequest', to='connexionapi.connexionuser'),
        ),
    ]
